---
title: "Manufacturing"
format: html
editor: visual
---

```{r}
#| message: false
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
```

```{r}
mex_ts_tbl <- tribble(
  ~code, ~description, ~seasonal, ~ units,
  "MAUINSA", "Mexican Auto Imports", TRUE, "Thousands of Units",
  "HOHWMN03MXM661N", "Hours Worked: Manufacturing: Monthly for Mexico", TRUE, "Index 2015=100",
  "OPCNSH01MXM661N", "Total Cost of Social Housing Construction for Mexico", FALSE, "Index 2015=100",
  "LCEAMN04MXM661N", "Manufacturing: Real Monthly Earnings for Mexico", TRUE, "Index 2015=100",
  "LRHUTTFEMXM156N", "Monthly Unemployment Rate Female: 15 Years or over for Mexico", TRUE, "Percent",
  "LRHUTTMAMXM156N", "Monthly Unemployment Rate Male: 15 Years or over for Mexico", TRUE, "Percent",
  "MEDLISPRIPERSQUFEE33020", "Median Listing Price per Square Feet in Mexico, MO (CBSA)", FALSE, "USD",
  "IMPMX", "U.S. Imports of Goods by Customs Basis from Mexico", TRUE, "Millions of Dollars",
  "MEXPRMNTO01IXOBM", "Manufacturing for Mexico", TRUE, "Index 2015=100",
  "MEXXTIMVA01NCMLM", "Imports: Commodities for Mexico", FALSE, "Mexican Peso"
)

mex_ts_names <- mex_ts_tbl |> 
  pull(code)
```


```{r}
manufactura <- tidyquant::tq_get(
  "MEXPRMNTO01IXOBM",
  get = "economic.data",
  from = "1980-01-01"
) |> 
  mutate(
    date = yearmonth(date)
  ) |> 
  as_tsibble(index = date)

manufactura

manufactura_train <- manufactura |> 
  filter_index(. ~ "2023 mar.")

manufactura_train

manufactura_train |> 
  autoplot(price)
```

```{r}
manufactura_train |> 
  model(
    STL(log(price) ~ season(window = "periodic"), robust = TRUE)
  ) |> 
  components() |> 
  autoplot()

manufactura_train |> 
  model(
    benchmark = decomposition_model(
      STL(log(price) ~ season(window = "periodic"), robust = TRUE),
      RW(season_adjust ~ drift())
    )
  ) |> 
  forecast(h = 12) |> 
  autoplot(manufactura)
```



##

```{r}
manufactura |> 
  autoplot(price)
```

```{r}
tsbls <- tidyquant::tq_get(
  mex_ts_names,
  get = "economic.data",
  from = "1980-01-01"
) |> 
  mutate(
    date = yearmonth(date)
  ) |> 
  as_tsibble(index = date, key = symbol)

tsbls
```

```{r}
tsbls |> 
  autoplot(price) + 
  facet_wrap(vars(symbol), scales = "free") + 
  theme(legend.position = "none")
```

```{r}
tictoc::tic()
turismo_fit <- tourism |> 
  model(
    ets = ETS(Trips ~ trend(c("A","Ad")) + season(c("A", "M")))
  )
tictoc::toc()
turismo_fit
```


```{r}
tictoc::tic()
turismo_fcst <- turismo_fit |> 
  forecast(h = "3 years")
tictoc::toc()

turismo_fcst
```



```{r}
tictoc::tic()
tsbls_fit <- tsbls |> 
  model(
    ets = ETS(log(price))
  ) 
tictoc::toc()
tsbls_fit

tsbls_fit |> 
  augment() |> 
  features(.innov, features = ljung_box, lag = 24)

tsbls_fcst <- tsbls_fit |> 
  forecast(h = "5 years") 

tsbls_fcst |> 
  autoplot(tsbls) +
  facet_wrap(vars(symbol), scales = "free")
```

```{r}
tsbls |> 
  pivot_wider(
    names_from = symbol,
    values_from = price
  ) |> 
  pivot_longer(
    cols = - date,
    names_to = "variable",
    values_to = "valor"
  )
```

